exception: pretty printing to writer with context
This commit replaces SyntaxViolation.debug with

    /// pretty print a SyntaxViolation, heavily inspired by
    /// [T8Err::render](https://github.com/xnacly/tango8/blob/master/shared/src/err.rs#L11)
    pub fn pretty_print<'r, W, S>(&self, w: &'r mut W, lines: &'r [S]) -> io::Result<()>
    where
        W: std::io::Write,
        S: std::fmt::Display,

    /// The repl doesnt allow us to capture all input lines via the fs, so we need a fallback for
    /// only printing the offending line, we have access to via gc_inner
    pub fn pretty_print_no_lines<W>(&self, w: &mut W) -> io::Result<()>
    where
        W: std::io::Write,

Enabling the pretty exception printing to support both the repl and the
file based execution mode. Both functions print context, specifically
the previous and following line relative to the offending name